/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CronResult,
    CronResultFromJSON,
    CronResultToJSON,
    SystemInfo,
    SystemInfoFromJSON,
    SystemInfoToJSON,
    UserSingle,
    UserSingleFromJSON,
    UserSingleToJSON,
} from '../models';

export interface GetCronRequest {
    cliToken: string;
    date?: Date;
    force?: boolean;
}

/**
 * 
 */
export class AboutApi extends runtime.BaseAPI {

    /**
     * Returns general system information and versions of the (supporting) software. 
     * System information end point.
     */
    async getAboutRaw(): Promise<runtime.ApiResponse<SystemInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/about`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemInfoFromJSON(jsonValue));
    }

    /**
     * Returns general system information and versions of the (supporting) software. 
     * System information end point.
     */
    async getAbout(): Promise<SystemInfo> {
        const response = await this.getAboutRaw();
        return await response.value();
    }

    /**
     * Firefly III has one endpoint for its various cron related tasks. Send a GET to this endpoint to run the cron. The cron requires the CLI token to be present. The cron job will fire for all users. 
     * Cron job endpoint
     */
    async getCronRaw(requestParameters: GetCronRequest): Promise<runtime.ApiResponse<CronResult>> {
        if (requestParameters.cliToken === null || requestParameters.cliToken === undefined) {
            throw new runtime.RequiredError('cliToken','Required parameter requestParameters.cliToken was null or undefined when calling getCron.');
        }

        const queryParameters: any = {};

        if (requestParameters.date !== undefined) {
            queryParameters['date'] = (requestParameters.date as any).toISOString().substr(0,10);
        }

        if (requestParameters.force !== undefined) {
            queryParameters['force'] = requestParameters.force;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/cron/{cliToken}`.replace(`{${"cliToken"}}`, encodeURIComponent(String(requestParameters.cliToken))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CronResultFromJSON(jsonValue));
    }

    /**
     * Firefly III has one endpoint for its various cron related tasks. Send a GET to this endpoint to run the cron. The cron requires the CLI token to be present. The cron job will fire for all users. 
     * Cron job endpoint
     */
    async getCron(requestParameters: GetCronRequest): Promise<CronResult> {
        const response = await this.getCronRaw(requestParameters);
        return await response.value();
    }

    /**
     * Returns the currently authenticated user. 
     * Currently authenticated user endpoint.
     */
    async getCurrentUserRaw(): Promise<runtime.ApiResponse<UserSingle>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/about/user`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSingleFromJSON(jsonValue));
    }

    /**
     * Returns the currently authenticated user. 
     * Currently authenticated user endpoint.
     */
    async getCurrentUser(): Promise<UserSingle> {
        const response = await this.getCurrentUserRaw();
        return await response.value();
    }

}
