/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AttachmentArray,
    AttachmentArrayFromJSON,
    AttachmentArrayToJSON,
    BillArray,
    BillArrayFromJSON,
    BillArrayToJSON,
    BillSingle,
    BillSingleFromJSON,
    BillSingleToJSON,
    BillStore,
    BillStoreFromJSON,
    BillStoreToJSON,
    BillUpdate,
    BillUpdateFromJSON,
    BillUpdateToJSON,
    RuleArray,
    RuleArrayFromJSON,
    RuleArrayToJSON,
    TransactionArray,
    TransactionArrayFromJSON,
    TransactionArrayToJSON,
    TransactionTypeFilter,
    TransactionTypeFilterFromJSON,
    TransactionTypeFilterToJSON,
    ValidationError,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from '../models';

export interface DeleteBillRequest {
    id: string;
}

export interface GetBillRequest {
    id: string;
    start?: Date;
    end?: Date;
}

export interface ListAttachmentByBillRequest {
    id: string;
    page?: number;
}

export interface ListBillRequest {
    page?: number;
    start?: Date;
    end?: Date;
}

export interface ListRuleByBillRequest {
    id: string;
}

export interface ListTransactionByBillRequest {
    id: string;
    start?: Date;
    end?: Date;
    type?: TransactionTypeFilter;
}

export interface StoreBillRequest {
    billStore: BillStore;
}

export interface UpdateBillRequest {
    id: string;
    billUpdate: BillUpdate;
}

/**
 * 
 */
export class BillsApi extends runtime.BaseAPI {

    /**
     * Delete a bill. This will not delete any associated rules. Will not remove associated transactions. WILL remove all associated attachments.
     * Delete a bill.
     */
    async deleteBillRaw(requestParameters: DeleteBillRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteBill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a bill. This will not delete any associated rules. Will not remove associated transactions. WILL remove all associated attachments.
     * Delete a bill.
     */
    async deleteBill(requestParameters: DeleteBillRequest): Promise<void> {
        await this.deleteBillRaw(requestParameters);
    }

    /**
     * Get a single bill.
     * Get a single bill.
     */
    async getBillRaw(requestParameters: GetBillRequest): Promise<runtime.ApiResponse<BillSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getBill.');
        }

        const queryParameters: any = {};

        if (requestParameters.start !== undefined) {
            queryParameters['start'] = (requestParameters.start as any).toISOString().substr(0,10);
        }

        if (requestParameters.end !== undefined) {
            queryParameters['end'] = (requestParameters.end as any).toISOString().substr(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BillSingleFromJSON(jsonValue));
    }

    /**
     * Get a single bill.
     * Get a single bill.
     */
    async getBill(requestParameters: GetBillRequest): Promise<BillSingle> {
        const response = await this.getBillRaw(requestParameters);
        return await response.value();
    }

    /**
     * This endpoint will list all attachments linked to the bill.
     * List all attachments uploaded to the bill.
     */
    async listAttachmentByBillRaw(requestParameters: ListAttachmentByBillRequest): Promise<runtime.ApiResponse<AttachmentArray>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listAttachmentByBill.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills/{id}/attachments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AttachmentArrayFromJSON(jsonValue));
    }

    /**
     * This endpoint will list all attachments linked to the bill.
     * List all attachments uploaded to the bill.
     */
    async listAttachmentByBill(requestParameters: ListAttachmentByBillRequest): Promise<AttachmentArray> {
        const response = await this.listAttachmentByBillRaw(requestParameters);
        return await response.value();
    }

    /**
     * This endpoint will list all the user\'s bills.
     * List all bills.
     */
    async listBillRaw(requestParameters: ListBillRequest): Promise<runtime.ApiResponse<BillArray>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['start'] = (requestParameters.start as any).toISOString().substr(0,10);
        }

        if (requestParameters.end !== undefined) {
            queryParameters['end'] = (requestParameters.end as any).toISOString().substr(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BillArrayFromJSON(jsonValue));
    }

    /**
     * This endpoint will list all the user\'s bills.
     * List all bills.
     */
    async listBill(requestParameters: ListBillRequest): Promise<BillArray> {
        const response = await this.listBillRaw(requestParameters);
        return await response.value();
    }

    /**
     * This endpoint will list all rules that have an action to set the bill to this bill.
     * List all rules associated with the bill.
     */
    async listRuleByBillRaw(requestParameters: ListRuleByBillRequest): Promise<runtime.ApiResponse<RuleArray>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listRuleByBill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills/{id}/rules`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => RuleArrayFromJSON(jsonValue));
    }

    /**
     * This endpoint will list all rules that have an action to set the bill to this bill.
     * List all rules associated with the bill.
     */
    async listRuleByBill(requestParameters: ListRuleByBillRequest): Promise<RuleArray> {
        const response = await this.listRuleByBillRaw(requestParameters);
        return await response.value();
    }

    /**
     * This endpoint will list all transactions linked to this bill.
     * List all transactions associated with the  bill.
     */
    async listTransactionByBillRaw(requestParameters: ListTransactionByBillRequest): Promise<runtime.ApiResponse<TransactionArray>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listTransactionByBill.');
        }

        const queryParameters: any = {};

        if (requestParameters.start !== undefined) {
            queryParameters['start'] = (requestParameters.start as any).toISOString().substr(0,10);
        }

        if (requestParameters.end !== undefined) {
            queryParameters['end'] = (requestParameters.end as any).toISOString().substr(0,10);
        }

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills/{id}/transactions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionArrayFromJSON(jsonValue));
    }

    /**
     * This endpoint will list all transactions linked to this bill.
     * List all transactions associated with the  bill.
     */
    async listTransactionByBill(requestParameters: ListTransactionByBillRequest): Promise<TransactionArray> {
        const response = await this.listTransactionByBillRaw(requestParameters);
        return await response.value();
    }

    /**
     * Creates a new bill. The data required can be submitted as a JSON body or as a list of parameters.
     * Store a new bill
     */
    async storeBillRaw(requestParameters: StoreBillRequest): Promise<runtime.ApiResponse<BillSingle>> {
        if (requestParameters.billStore === null || requestParameters.billStore === undefined) {
            throw new runtime.RequiredError('billStore','Required parameter requestParameters.billStore was null or undefined when calling storeBill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BillStoreToJSON(requestParameters.billStore),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BillSingleFromJSON(jsonValue));
    }

    /**
     * Creates a new bill. The data required can be submitted as a JSON body or as a list of parameters.
     * Store a new bill
     */
    async storeBill(requestParameters: StoreBillRequest): Promise<BillSingle> {
        const response = await this.storeBillRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update existing bill.
     * Update existing bill.
     */
    async updateBillRaw(requestParameters: UpdateBillRequest): Promise<runtime.ApiResponse<BillSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateBill.');
        }

        if (requestParameters.billUpdate === null || requestParameters.billUpdate === undefined) {
            throw new runtime.RequiredError('billUpdate','Required parameter requestParameters.billUpdate was null or undefined when calling updateBill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/bills/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BillUpdateToJSON(requestParameters.billUpdate),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BillSingleFromJSON(jsonValue));
    }

    /**
     * Update existing bill.
     * Update existing bill.
     */
    async updateBill(requestParameters: UpdateBillRequest): Promise<BillSingle> {
        const response = await this.updateBillRaw(requestParameters);
        return await response.value();
    }

}
