/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Preference,
    PreferenceFromJSON,
    PreferenceToJSON,
    PreferenceArray,
    PreferenceArrayFromJSON,
    PreferenceArrayToJSON,
    PreferenceSingle,
    PreferenceSingleFromJSON,
    PreferenceSingleToJSON,
    PreferenceUpdate,
    PreferenceUpdateFromJSON,
    PreferenceUpdateToJSON,
    ValidationError,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from '../models';

export interface GetPreferenceRequest {
    name: string;
}

export interface ListPreferenceRequest {
    page?: number;
}

export interface StorePreferenceRequest {
    preference: Preference;
}

export interface UpdatePreferenceRequest {
    name: string;
    preferenceUpdate: PreferenceUpdate;
}

/**
 * 
 */
export class PreferencesApi extends runtime.BaseAPI {

    /**
     * Return a single preference and the value.
     * Return a single preference.
     */
    async getPreferenceRaw(requestParameters: GetPreferenceRequest): Promise<runtime.ApiResponse<PreferenceSingle>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling getPreference.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/preferences/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PreferenceSingleFromJSON(jsonValue));
    }

    /**
     * Return a single preference and the value.
     * Return a single preference.
     */
    async getPreference(requestParameters: GetPreferenceRequest): Promise<PreferenceSingle> {
        const response = await this.getPreferenceRaw(requestParameters);
        return await response.value();
    }

    /**
     * List all of the preferences of the user.
     * List all users preferences.
     */
    async listPreferenceRaw(requestParameters: ListPreferenceRequest): Promise<runtime.ApiResponse<PreferenceArray>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/preferences`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PreferenceArrayFromJSON(jsonValue));
    }

    /**
     * List all of the preferences of the user.
     * List all users preferences.
     */
    async listPreference(requestParameters: ListPreferenceRequest): Promise<PreferenceArray> {
        const response = await this.listPreferenceRaw(requestParameters);
        return await response.value();
    }

    /**
     * This endpoint creates a new preference. The name and data are free-format, and entirely up to you. If the preference is not used in Firefly III itself it may not be configurable through the user interface, but you can use this endpoint to persist custom data for your own app.
     * Store a new preference for this user.
     */
    async storePreferenceRaw(requestParameters: StorePreferenceRequest): Promise<runtime.ApiResponse<PreferenceSingle>> {
        if (requestParameters.preference === null || requestParameters.preference === undefined) {
            throw new runtime.RequiredError('preference','Required parameter requestParameters.preference was null or undefined when calling storePreference.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/preferences`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PreferenceToJSON(requestParameters.preference),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PreferenceSingleFromJSON(jsonValue));
    }

    /**
     * This endpoint creates a new preference. The name and data are free-format, and entirely up to you. If the preference is not used in Firefly III itself it may not be configurable through the user interface, but you can use this endpoint to persist custom data for your own app.
     * Store a new preference for this user.
     */
    async storePreference(requestParameters: StorePreferenceRequest): Promise<PreferenceSingle> {
        const response = await this.storePreferenceRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update a user\'s preference.
     * Update preference
     */
    async updatePreferenceRaw(requestParameters: UpdatePreferenceRequest): Promise<runtime.ApiResponse<PreferenceSingle>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling updatePreference.');
        }

        if (requestParameters.preferenceUpdate === null || requestParameters.preferenceUpdate === undefined) {
            throw new runtime.RequiredError('preferenceUpdate','Required parameter requestParameters.preferenceUpdate was null or undefined when calling updatePreference.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("firefly_iii_auth", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/api/v1/preferences/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PreferenceUpdateToJSON(requestParameters.preferenceUpdate),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PreferenceSingleFromJSON(jsonValue));
    }

    /**
     * Update a user\'s preference.
     * Update preference
     */
    async updatePreference(requestParameters: UpdatePreferenceRequest): Promise<PreferenceSingle> {
        const response = await this.updatePreferenceRaw(requestParameters);
        return await response.value();
    }

}
