/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountRead,
    AccountReadFromJSON,
    AccountReadFromJSONTyped,
    AccountReadToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountSingle
 */
export interface AccountSingle {
    /**
     * 
     * @type {AccountRead}
     * @memberof AccountSingle
     */
    data: AccountRead;
}

export function AccountSingleFromJSON(json: any): AccountSingle {
    return AccountSingleFromJSONTyped(json, false);
}

export function AccountSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSingle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AccountReadFromJSON(json['data']),
    };
}

export function AccountSingleToJSON(value?: AccountSingle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AccountReadToJSON(value.data),
    };
}


