/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteObjectGroup
 */
export interface AutocompleteObjectGroup {
    /**
     * 
     * @type {string}
     * @memberof AutocompleteObjectGroup
     */
    id: string;
    /**
     * Title of the object group found by an auto-complete search.
     * @type {string}
     * @memberof AutocompleteObjectGroup
     */
    title: string;
    /**
     * Title of the object group found by an auto-complete search.
     * @type {string}
     * @memberof AutocompleteObjectGroup
     */
    name: string;
}

export function AutocompleteObjectGroupFromJSON(json: any): AutocompleteObjectGroup {
    return AutocompleteObjectGroupFromJSONTyped(json, false);
}

export function AutocompleteObjectGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteObjectGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'name': json['name'],
    };
}

export function AutocompleteObjectGroupToJSON(value?: AutocompleteObjectGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'name': value.name,
    };
}


