/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteTransaction
 */
export interface AutocompleteTransaction {
    /**
     * The ID of a transaction journal (basically a single split).
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    id: string;
    /**
     * The ID of the underlying transaction group.
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    transactionGroupId?: string;
    /**
     * Transaction description
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    name: string;
    /**
     * Transaction description
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    description: string;
}

export function AutocompleteTransactionFromJSON(json: any): AutocompleteTransaction {
    return AutocompleteTransactionFromJSONTyped(json, false);
}

export function AutocompleteTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'transactionGroupId': !exists(json, 'transaction_group_id') ? undefined : json['transaction_group_id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function AutocompleteTransactionToJSON(value?: AutocompleteTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'transaction_group_id': value.transactionGroupId,
        'name': value.name,
        'description': value.description,
    };
}


