/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompletePiggy
 */
export interface AutocompletePiggy {
    /**
     * 
     * @type {string}
     * @memberof AutocompletePiggy
     */
    id: string;
    /**
     * Name of the piggy bank found by an auto-complete search.
     * @type {string}
     * @memberof AutocompletePiggy
     */
    name: string;
    /**
     * Currency ID for this piggy bank.
     * @type {string}
     * @memberof AutocompletePiggy
     */
    currencyId?: string;
    /**
     * Currency code for this piggy bank.
     * @type {string}
     * @memberof AutocompletePiggy
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AutocompletePiggy
     */
    currencySymbol?: string;
    /**
     * Currency name for the currency used by this account.
     * @type {string}
     * @memberof AutocompletePiggy
     */
    currencyName?: string;
    /**
     * 
     * @type {number}
     * @memberof AutocompletePiggy
     */
    currencyDecimalPlaces?: number;
    /**
     * The group ID of the group this object is part of. NULL if no group.
     * @type {string}
     * @memberof AutocompletePiggy
     */
    objectGroupId?: string | null;
    /**
     * The name of the group. NULL if no group.
     * @type {string}
     * @memberof AutocompletePiggy
     */
    objectGroupTitle?: string | null;
}

export function AutocompletePiggyFromJSON(json: any): AutocompletePiggy {
    return AutocompletePiggyFromJSONTyped(json, false);
}

export function AutocompletePiggyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompletePiggy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'currencyId': !exists(json, 'currency_id') ? undefined : json['currency_id'],
        'currencyCode': !exists(json, 'currency_code') ? undefined : json['currency_code'],
        'currencySymbol': !exists(json, 'currency_symbol') ? undefined : json['currency_symbol'],
        'currencyName': !exists(json, 'currency_name') ? undefined : json['currency_name'],
        'currencyDecimalPlaces': !exists(json, 'currency_decimal_places') ? undefined : json['currency_decimal_places'],
        'objectGroupId': !exists(json, 'object_group_id') ? undefined : json['object_group_id'],
        'objectGroupTitle': !exists(json, 'object_group_title') ? undefined : json['object_group_title'],
    };
}

export function AutocompletePiggyToJSON(value?: AutocompletePiggy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'currency_id': value.currencyId,
        'currency_code': value.currencyCode,
        'currency_symbol': value.currencySymbol,
        'currency_name': value.currencyName,
        'currency_decimal_places': value.currencyDecimalPlaces,
        'object_group_id': value.objectGroupId,
        'object_group_title': value.objectGroupTitle,
    };
}


