/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillPaidDates
 */
export interface BillPaidDates {
    /**
     * Transaction group ID of the paid bill.
     * @type {string}
     * @memberof BillPaidDates
     */
    readonly transactionGroupId?: string;
    /**
     * Transaction journal ID of the paid bill.
     * @type {string}
     * @memberof BillPaidDates
     */
    readonly transactionJournalId?: string;
    /**
     * Date the bill was paid.
     * @type {Date}
     * @memberof BillPaidDates
     */
    readonly date?: Date;
}

export function BillPaidDatesFromJSON(json: any): BillPaidDates {
    return BillPaidDatesFromJSONTyped(json, false);
}

export function BillPaidDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillPaidDates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionGroupId': !exists(json, 'transaction_group_id') ? undefined : json['transaction_group_id'],
        'transactionJournalId': !exists(json, 'transaction_journal_id') ? undefined : json['transaction_journal_id'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
    };
}

export function BillPaidDatesToJSON(value?: BillPaidDates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


