/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BudgetLimitRead,
    BudgetLimitReadFromJSON,
    BudgetLimitReadFromJSONTyped,
    BudgetLimitReadToJSON,
} from './';

/**
 * 
 * @export
 * @interface BudgetLimitSingle
 */
export interface BudgetLimitSingle {
    /**
     * 
     * @type {BudgetLimitRead}
     * @memberof BudgetLimitSingle
     */
    data: BudgetLimitRead;
}

export function BudgetLimitSingleFromJSON(json: any): BudgetLimitSingle {
    return BudgetLimitSingleFromJSONTyped(json, false);
}

export function BudgetLimitSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetLimitSingle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': BudgetLimitReadFromJSON(json['data']),
    };
}

export function BudgetLimitSingleToJSON(value?: BudgetLimitSingle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': BudgetLimitReadToJSON(value.data),
    };
}


