/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AutoBudgetPeriod,
    AutoBudgetPeriodFromJSON,
    AutoBudgetPeriodFromJSONTyped,
    AutoBudgetPeriodToJSON,
    AutoBudgetType,
    AutoBudgetTypeFromJSON,
    AutoBudgetTypeFromJSONTyped,
    AutoBudgetTypeToJSON,
    BudgetSpent,
    BudgetSpentFromJSON,
    BudgetSpentFromJSONTyped,
    BudgetSpentToJSON,
} from './';

/**
 * 
 * @export
 * @interface Budget
 */
export interface Budget {
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof Budget
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    readonly order?: number;
    /**
     * 
     * @type {AutoBudgetType}
     * @memberof Budget
     */
    autoBudgetType?: AutoBudgetType | null;
    /**
     * Use either currency_id or currency_code. Defaults to the user's default currency.
     * @type {string}
     * @memberof Budget
     */
    autoBudgetCurrencyId?: string | null;
    /**
     * Use either currency_id or currency_code. Defaults to the user's default currency.
     * @type {string}
     * @memberof Budget
     */
    autoBudgetCurrencyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    autoBudgetAmount?: string | null;
    /**
     * 
     * @type {AutoBudgetPeriod}
     * @memberof Budget
     */
    autoBudgetPeriod?: AutoBudgetPeriod | null;
    /**
     * Information on how much was spent in this budget. Is only filled in when the start and end date are submitted.
     * @type {Array<BudgetSpent>}
     * @memberof Budget
     */
    readonly spent?: Array<BudgetSpent>;
}

export function BudgetFromJSON(json: any): Budget {
    return BudgetFromJSONTyped(json, false);
}

export function BudgetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Budget {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'name': json['name'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'autoBudgetType': !exists(json, 'auto_budget_type') ? undefined : AutoBudgetTypeFromJSON(json['auto_budget_type']),
        'autoBudgetCurrencyId': !exists(json, 'auto_budget_currency_id') ? undefined : json['auto_budget_currency_id'],
        'autoBudgetCurrencyCode': !exists(json, 'auto_budget_currency_code') ? undefined : json['auto_budget_currency_code'],
        'autoBudgetAmount': !exists(json, 'auto_budget_amount') ? undefined : json['auto_budget_amount'],
        'autoBudgetPeriod': !exists(json, 'auto_budget_period') ? undefined : AutoBudgetPeriodFromJSON(json['auto_budget_period']),
        'spent': !exists(json, 'spent') ? undefined : ((json['spent'] as Array<any>).map(BudgetSpentFromJSON)),
    };
}

export function BudgetToJSON(value?: Budget | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'active': value.active,
        'notes': value.notes,
        'auto_budget_type': AutoBudgetTypeToJSON(value.autoBudgetType),
        'auto_budget_currency_id': value.autoBudgetCurrencyId,
        'auto_budget_currency_code': value.autoBudgetCurrencyCode,
        'auto_budget_amount': value.autoBudgetAmount,
        'auto_budget_period': AutoBudgetPeriodToJSON(value.autoBudgetPeriod),
    };
}


