/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BudgetLimitRead,
    BudgetLimitReadFromJSON,
    BudgetLimitReadFromJSONTyped,
    BudgetLimitReadToJSON,
    Meta,
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface BudgetLimitArray
 */
export interface BudgetLimitArray {
    /**
     * 
     * @type {Array<BudgetLimitRead>}
     * @memberof BudgetLimitArray
     */
    data: Array<BudgetLimitRead>;
    /**
     * 
     * @type {Meta}
     * @memberof BudgetLimitArray
     */
    meta: Meta;
}

export function BudgetLimitArrayFromJSON(json: any): BudgetLimitArray {
    return BudgetLimitArrayFromJSONTyped(json, false);
}

export function BudgetLimitArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetLimitArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BudgetLimitReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function BudgetLimitArrayToJSON(value?: BudgetLimitArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(BudgetLimitReadToJSON)),
        'meta': MetaToJSON(value.meta),
    };
}


