/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BudgetSpent
 */
export interface BudgetSpent {
    /**
     * The amount spent.
     * @type {string}
     * @memberof BudgetSpent
     */
    sum?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetSpent
     */
    currencyId?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetSpent
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetSpent
     */
    currencySymbol?: string;
    /**
     * Number of decimals supported by the currency
     * @type {number}
     * @memberof BudgetSpent
     */
    currencyDecimalPlaces?: number;
}

export function BudgetSpentFromJSON(json: any): BudgetSpent {
    return BudgetSpentFromJSONTyped(json, false);
}

export function BudgetSpentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetSpent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sum': !exists(json, 'sum') ? undefined : json['sum'],
        'currencyId': !exists(json, 'currency_id') ? undefined : json['currency_id'],
        'currencyCode': !exists(json, 'currency_code') ? undefined : json['currency_code'],
        'currencySymbol': !exists(json, 'currency_symbol') ? undefined : json['currency_symbol'],
        'currencyDecimalPlaces': !exists(json, 'currency_decimal_places') ? undefined : json['currency_decimal_places'],
    };
}

export function BudgetSpentToJSON(value?: BudgetSpent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sum': value.sum,
        'currency_id': value.currencyId,
        'currency_code': value.currencyCode,
        'currency_symbol': value.currencySymbol,
        'currency_decimal_places': value.currencyDecimalPlaces,
    };
}


