/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Category,
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './';

/**
 * 
 * @export
 * @interface CategoryRead
 */
export interface CategoryRead {
    /**
     * Immutable value
     * @type {string}
     * @memberof CategoryRead
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryRead
     */
    id: string;
    /**
     * 
     * @type {Category}
     * @memberof CategoryRead
     */
    attributes: Category;
}

export function CategoryReadFromJSON(json: any): CategoryRead {
    return CategoryReadFromJSONTyped(json, false);
}

export function CategoryReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': CategoryFromJSON(json['attributes']),
    };
}

export function CategoryReadToJSON(value?: CategoryRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': CategoryToJSON(value.attributes),
    };
}


