/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CategoryRead,
    CategoryReadFromJSON,
    CategoryReadFromJSONTyped,
    CategoryReadToJSON,
} from './';

/**
 * 
 * @export
 * @interface CategorySingle
 */
export interface CategorySingle {
    /**
     * 
     * @type {CategoryRead}
     * @memberof CategorySingle
     */
    data: CategoryRead;
}

export function CategorySingleFromJSON(json: any): CategorySingle {
    return CategorySingleFromJSONTyped(json, false);
}

export function CategorySingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySingle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CategoryReadFromJSON(json['data']),
    };
}

export function CategorySingleToJSON(value?: CategorySingle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CategoryReadToJSON(value.data),
    };
}


