/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChartDataPoint
 */
export interface ChartDataPoint {
    /**
     * The key is the label of the value, so for example: '2018-01-01' => 13 or 'Groceries' => -123.
     * @type {string}
     * @memberof ChartDataPoint
     */
    key?: string;
}

export function ChartDataPointFromJSON(json: any): ChartDataPoint {
    return ChartDataPointFromJSONTyped(json, false);
}

export function ChartDataPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartDataPoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function ChartDataPointToJSON(value?: ChartDataPoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}


