/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CronResultRow,
    CronResultRowFromJSON,
    CronResultRowFromJSONTyped,
    CronResultRowToJSON,
} from './';

/**
 * 
 * @export
 * @interface CronResult
 */
export interface CronResult {
    /**
     * 
     * @type {CronResultRow}
     * @memberof CronResult
     */
    recurringTransactions?: CronResultRow;
    /**
     * 
     * @type {CronResultRow}
     * @memberof CronResult
     */
    autoBudgets?: CronResultRow;
    /**
     * 
     * @type {CronResultRow}
     * @memberof CronResult
     */
    telemetry?: CronResultRow;
}

export function CronResultFromJSON(json: any): CronResult {
    return CronResultFromJSONTyped(json, false);
}

export function CronResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CronResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recurringTransactions': !exists(json, 'recurring_transactions') ? undefined : CronResultRowFromJSON(json['recurring_transactions']),
        'autoBudgets': !exists(json, 'auto_budgets') ? undefined : CronResultRowFromJSON(json['auto_budgets']),
        'telemetry': !exists(json, 'telemetry') ? undefined : CronResultRowFromJSON(json['telemetry']),
    };
}

export function CronResultToJSON(value?: CronResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recurring_transactions': CronResultRowToJSON(value.recurringTransactions),
        'auto_budgets': CronResultRowToJSON(value.autoBudgets),
        'telemetry': CronResultRowToJSON(value.telemetry),
    };
}


