/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PolymorphicProperty,
    PolymorphicPropertyFromJSON,
    PolymorphicPropertyFromJSONTyped,
    PolymorphicPropertyToJSON,
} from './';

/**
 * 
 * @export
 * @interface PreferenceUpdate
 */
export interface PreferenceUpdate {
    /**
     * 
     * @type {PolymorphicProperty}
     * @memberof PreferenceUpdate
     */
    data: PolymorphicProperty;
}

export function PreferenceUpdateFromJSON(json: any): PreferenceUpdate {
    return PreferenceUpdateFromJSONTyped(json, false);
}

export function PreferenceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferenceUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': PolymorphicPropertyFromJSON(json['data']),
    };
}

export function PreferenceUpdateToJSON(value?: PreferenceUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': PolymorphicPropertyToJSON(value.data),
    };
}


