/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PolymorphicProperty,
    PolymorphicPropertyFromJSON,
    PolymorphicPropertyFromJSONTyped,
    PolymorphicPropertyToJSON,
} from './';

/**
 * 
 * @export
 * @interface Preference
 */
export interface Preference {
    /**
     * 
     * @type {Date}
     * @memberof Preference
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Preference
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Preference
     */
    name: string;
    /**
     * 
     * @type {PolymorphicProperty}
     * @memberof Preference
     */
    data: PolymorphicProperty;
}

export function PreferenceFromJSON(json: any): Preference {
    return PreferenceFromJSONTyped(json, false);
}

export function PreferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'name': json['name'],
        'data': PolymorphicPropertyFromJSON(json['data']),
    };
}

export function PreferenceToJSON(value?: Preference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'data': PolymorphicPropertyToJSON(value.data),
    };
}


