/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuleGroupStore
 */
export interface RuleGroupStore {
    /**
     * 
     * @type {string}
     * @memberof RuleGroupStore
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RuleGroupStore
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RuleGroupStore
     */
    order?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RuleGroupStore
     */
    active?: boolean;
}

export function RuleGroupStoreFromJSON(json: any): RuleGroupStore {
    return RuleGroupStoreFromJSONTyped(json, false);
}

export function RuleGroupStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleGroupStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'active': !exists(json, 'active') ? undefined : json['active'],
    };
}

export function RuleGroupStoreToJSON(value?: RuleGroupStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'order': value.order,
        'active': value.active,
    };
}


