/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    PageLink,
    PageLinkFromJSON,
    PageLinkFromJSONTyped,
    PageLinkToJSON,
    RuleRead,
    RuleReadFromJSON,
    RuleReadFromJSONTyped,
    RuleReadToJSON,
} from './';

/**
 * 
 * @export
 * @interface RuleArray
 */
export interface RuleArray {
    /**
     * 
     * @type {Array<RuleRead>}
     * @memberof RuleArray
     */
    data: Array<RuleRead>;
    /**
     * 
     * @type {Meta}
     * @memberof RuleArray
     */
    meta: Meta;
    /**
     * 
     * @type {PageLink}
     * @memberof RuleArray
     */
    links: PageLink;
}

export function RuleArrayFromJSON(json: any): RuleArray {
    return RuleArrayFromJSONTyped(json, false);
}

export function RuleArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RuleReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
        'links': PageLinkFromJSON(json['links']),
    };
}

export function RuleArrayToJSON(value?: RuleArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(RuleReadToJSON)),
        'meta': MetaToJSON(value.meta),
        'links': PageLinkToJSON(value.links),
    };
}


