/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Meta,
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    PageLink,
    PageLinkFromJSON,
    PageLinkFromJSONTyped,
    PageLinkToJSON,
    UserRead,
    UserReadFromJSON,
    UserReadFromJSONTyped,
    UserReadToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserArray
 */
export interface UserArray {
    /**
     * 
     * @type {Array<UserRead>}
     * @memberof UserArray
     */
    data: Array<UserRead>;
    /**
     * 
     * @type {Meta}
     * @memberof UserArray
     */
    meta: Meta;
    /**
     * 
     * @type {PageLink}
     * @memberof UserArray
     */
    links: PageLink;
}

export function UserArrayFromJSON(json: any): UserArray {
    return UserArrayFromJSONTyped(json, false);
}

export function UserArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
        'links': PageLinkFromJSON(json['links']),
    };
}

export function UserArrayToJSON(value?: UserArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UserReadToJSON)),
        'meta': MetaToJSON(value.meta),
        'links': PageLinkToJSON(value.links),
    };
}


