/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WebhookMessage,
    WebhookMessageFromJSON,
    WebhookMessageFromJSONTyped,
    WebhookMessageToJSON,
} from './';

/**
 * 
 * @export
 * @interface WebhookMessageRead
 */
export interface WebhookMessageRead {
    /**
     * Immutable value
     * @type {string}
     * @memberof WebhookMessageRead
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookMessageRead
     */
    id: string;
    /**
     * 
     * @type {WebhookMessage}
     * @memberof WebhookMessageRead
     */
    attributes: WebhookMessage;
}

export function WebhookMessageReadFromJSON(json: any): WebhookMessageRead {
    return WebhookMessageReadFromJSONTyped(json, false);
}

export function WebhookMessageReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookMessageRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': WebhookMessageFromJSON(json['attributes']),
    };
}

export function WebhookMessageReadToJSON(value?: WebhookMessageRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': WebhookMessageToJSON(value.attributes),
    };
}


