/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookMessage
 */
export interface WebhookMessage {
    /**
     * 
     * @type {Date}
     * @memberof WebhookMessage
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WebhookMessage
     */
    readonly updatedAt?: Date;
    /**
     * If this message is sent yet.
     * @type {boolean}
     * @memberof WebhookMessage
     */
    sent?: boolean;
    /**
     * If this message has errored out.
     * @type {boolean}
     * @memberof WebhookMessage
     */
    errored?: boolean;
    /**
     * The ID of the webhook this message belongs to.
     * @type {string}
     * @memberof WebhookMessage
     */
    webhookId?: string;
    /**
     * Long UUID string for identification of this webhook message.
     * @type {string}
     * @memberof WebhookMessage
     */
    uuid?: string;
    /**
     * The actual message that is sent or will be sent as JSON string.
     * @type {string}
     * @memberof WebhookMessage
     */
    string?: string | null;
}

export function WebhookMessageFromJSON(json: any): WebhookMessage {
    return WebhookMessageFromJSONTyped(json, false);
}

export function WebhookMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'sent': !exists(json, 'sent') ? undefined : json['sent'],
        'errored': !exists(json, 'errored') ? undefined : json['errored'],
        'webhookId': !exists(json, 'webhook_id') ? undefined : json['webhook_id'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'string': !exists(json, 'string') ? undefined : json['string'],
    };
}

export function WebhookMessageToJSON(value?: WebhookMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sent': value.sent,
        'errored': value.errored,
        'webhook_id': value.webhookId,
        'uuid': value.uuid,
        'string': value.string,
    };
}


